routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/*
  DB::listen(function ($query){
  echo "<pre> {$query->sql} </pre>";
  });
 */

Route::get('/reset', function () {
    echo Artisan::call("migrate:refresh");
    echo Artisan::call("db:seed");
    return "PAGINA RESETEADA";
});

Route::get('/', function (Illuminate\Http\Request $request) {
    //dd($request->session()->all());
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

 Route::get('/sychronize', 'SychronizeController@synchronize')->name('sychronize');
 Route::get('/api/projects', 'FreedCampAPI\ProjectsAPIController@index')->name('api.projects');
 Route::get('/api/task', 'FreedCampAPI\TaskAPIController@index')->name('api.task');

Route::middleware('auth')->namespace('Resource')->group(function() {
    
   
    
    Route::resource('project', 'ProjectController');
    Route::resource('contract', 'ContractController');
    Route::resource('enterprise', 'EnterpriseController');
    Route::resource('task', 'TaskController');
    Route::resource('enterpriseservice', 'EnterpriseServiceController');
    Route::resource('client', 'ClientController');
    Route::resource('service', 'ServiceController');
    Route::resource('user', 'UserController');
    
    
    Route::GET('contract/{contract}/changeStatus/{status}' , 'ContractController@changeStatus')
            ->name('contract.changeStatus');
    
    Route::GET('task/{task}/changeStatus/{status}' , 'TaskController@changeStatus')
            ->name('task.changeStatus');
    
    Route::GET('project/{project}/setContract/{contract}' , 'ProjectController@setContract')
            ->name('project.setContract');
    
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model 
{

    protected $table = 'services';
    public $timestamps = true;

    
    public function enterprises()
    {
        return $this->belongsToMany('App\Enterprise')->using('App\EnterpriseService');
    }

    
    public function decorate(){
        return new \App\Decorators\ServiceDecorator($this);
    }
}

app/Http/Controllers/Resource/ServiceController.php
<?php

namespace App\Http\Controllers\Resource;

use App\Http\Controllers\Controller;
use App\service;
use Illuminate\Http\Request;
use App\Http\Requests\ServiceCreateRequest;

class ServiceController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $services = service::get();
        return view('models.service.home', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('models.service.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ServiceCreateRequest $request) {
        $service = new Service();
        $service->name = $request->input('name');
        $service->save();
        return redirect()->route('service.index');        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(service $service) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(service $service) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, service $service) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(service $service) {
        //
    }

}

resources/views/models/service/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="cabecera"> Crear un Servicio Nuevo </div>

                <div class="card-body text-center">

                    <form method="POST" action="{{ route('service.store') }}"  enctype="multipart/form-data">
                        @csrf


                        <div 
                            class="form-group row"
                            >
                            <label 
                                for="name" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Nombre') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >

                                <input id="name" 
                                       type="text"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="name" 
                                       value="{{ old('name') }}"
                                       required 
                                       autocomplete="name" 
                                       autofocus>

                                @error('name')
                                <span 
                                    class="invalid-feedback" 
                                    role="alert">
                                    <strong>
                                        {{ $message }}
                                    </strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div 
                            class="form-group row mb-0"
                            >
                            <div 
                                class="col-md-6 offset-md-4"
                                >
                                <button 
                                    type="submit" 
                                    class="btn btn-primary"
                                    >
                                    {{ __('Crear') }}
                                </button>
                            </div>
                        </div>


                    </form>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/service/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="cabecera">Bienvenido {{$user->name}} {{$user->last_name}} </div>

                <div class="card-body text-center">

                    <div class="col-lg-12 align-self-baseline ">
                        <p class=" font-weight-light mb-5"> Es un gusto tenerte por aquí de nuevo! </p>
                    </div>




                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/service/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="cabecera"> 
                    
                     Servicios
                
                </div>
                
               
                <div class="card-body">
                    
                     <p>
                        Tabla con los Servicios existentes.  
                    </p>
                    
                    <a 
                        class='btn btn-warning my-3'
                        href="{{route('service.create')}}"
                        >
                           Crear Servicio
                    </a>
                

                   @include('models.service.index')



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/service/index.blade.php
                        <table class='table table-sm table-striped ' >
                            <thead class='thead-dark '>
                                <tr>
                                    <th>
                                        id
                                    </th>
                                    <th>
                                        Nombre
                                    </th>
                                    <th>
                                        Fecha Creacion
                                    </th>
                                     <th>
                                        Fecha Actualizacion
                                    </th>
                                  
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ( $services as $service )

                                <tr>
                                     <th>
                                        {{$service->id}}
                                    </th>
                                    <th>
                                       {{ $service->decorate()->nameLink()}}
                                    </th>
                                    <th>
                                       {{ $service->created_at}}
                                    </th>
                                     <th>
                                       {{$service->updated_at}}
                                    </th>
                                                                     
                                    
                                </tr>

                                @endforeach
                            </tbody>
                        </table>