routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/*
  DB::listen(function ($query){
  echo "<pre> {$query->sql} </pre>";
  });
 */

Route::get('/reset', function () {
    echo Artisan::call("migrate:refresh");
    echo Artisan::call("db:seed");
    return "PAGINA RESETEADA";
});

Route::get('/', function (Illuminate\Http\Request $request) {
    //dd($request->session()->all());
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

 Route::get('/sychronize', 'SychronizeController@synchronize')->name('sychronize');
 Route::get('/api/projects', 'FreedCampAPI\ProjectsAPIController@index')->name('api.projects');
 Route::get('/api/task', 'FreedCampAPI\TaskAPIController@index')->name('api.task');

Route::middleware('auth')->namespace('Resource')->group(function() {
    
   
    
    Route::resource('project', 'ProjectController');
    Route::resource('contract', 'ContractController');
    Route::resource('enterprise', 'EnterpriseController');
    Route::resource('task', 'TaskController');
    Route::resource('enterpriseservice', 'EnterpriseServiceController');
    Route::resource('client', 'ClientController');
    Route::resource('service', 'ServiceController');
    Route::resource('user', 'UserController');
    
    
    Route::GET('contract/{contract}/changeStatus/{status}' , 'ContractController@changeStatus')
            ->name('contract.changeStatus');
    
    Route::GET('task/{task}/changeStatus/{status}' , 'TaskController@changeStatus')
            ->name('task.changeStatus');
    
    Route::GET('project/{project}/setContract/{contract}' , 'ProjectController@setContract')
            ->name('project.setContract');
    
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model {

    const STATUS_NOT_STARTED = 0;
    const STATUS_COMPLETED = 1;
    const STATUS_IN_PROGRESS = 2;
    const PRIORITY_NONE = 0;
    const PRIORITY_LOW = 1;
    const PRIORITY_MEDIUM = 2;
    const PRIORITY_HIGH = 3;
    
    const PRIORITY_ARRAY = [
        self::PRIORITY_NONE,
        self::PRIORITY_LOW,
        self::PRIORITY_MEDIUM,
        self::PRIORITY_HIGH,
    ];

    protected $table = 'tasks';
    public $timestamps = true;
    protected $with = ['project', 'assignedTo'];

    public function project() {
        return $this->belongsTo('App\Project', 'project_id', 'id');
    }

    public function assignedTo() {
        return $this->belongsTo('App\User', 'assigned_to', 'id');
    }

    public function decorate() {
        return new \App\Decorators\TaskDecorator($this);
    }

}

app/Http/Controllers/Resource/TaskController.php
<?php

namespace App\Http\Controllers\Resource;

use App\Http\Controllers\Controller;
use App\Task;
use App\Project;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\TaskCreateRequest;

class TaskController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $tasks = new Task();
        if($request->input('project_id')){
            $tasks = $tasks->where('project_id' ,$request->input('project_id') );
        }
        if($request->input('user_id')){
            $tasks = $tasks->where('assigned_to' ,$request->input('user_id') );
        }
        
        if($request->input('enterprise_id')){
           $tasks = Task::select('tasks.*')                             
                ->join('projects' , 'projects.id' , '=' , 'tasks.project_id')
                ->join('contracts' , 'projects.contract_id' , '=' , 'contracts.id')
                ->where('contracts.enterprise_id',  $request->input('enterprise_id'));          
                      
        }
        
        $tasks = $tasks->get();
        
        return view('models.Task.home', compact('tasks'));
    }

    public function changeStatus(Task $task, $status) {

        if ($status == Task::STATUS_COMPLETED) {
            $task->finished_at = now();
            $task->status = Task::STATUS_COMPLETED;
        } else if ($status == Task::STATUS_IN_PROGRESS) {
            $task->started_at = now();
            $task->finished_at = null;
            $task->status = Task::STATUS_IN_PROGRESS;
        } else if ($status == Task::STATUS_NOT_STARTED) {
            $task->finished_at = null;
            $task->started_at = null;
            $task->status = Task::STATUS_NOT_STARTED;
        } else {
            $error = ["error"];
            return back()->withErrors($error);
        }
        $task->save();
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $projects = Project::get();
        $users = User::get();
         return view('models.task.create', compact('projects' , 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskCreateRequest $request) {
        
        $task = new Task();
        $task->title = $request->input('name');
        $task->project_id = $request->input('project');
        $task->priority = $request->input('priority');
        $task->assigned_to = $request->input('user');
        $task->status = Task::STATUS_NOT_STARTED;
        $task->save();
        return redirect()->route('task.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task) {
        //
    }

}

resources/views/models/task/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="cabecera"> Crear un Servicio Nuevo </div>

                <div class="card-body text-center">

                    <form method="POST" action="{{ route('task.store') }}"  enctype="multipart/form-data">
                        @csrf


                        <div 
                            class="form-group row"
                            >
                            <label 
                                for="name" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Nombre') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >

                                <input id="name" 
                                       type="text"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="name" 
                                       value="{{ old('name') }}"
                                       required 
                                       autocomplete="name" 
                                       autofocus>

                                @error('name')
                                <span 
                                    class="invalid-feedback" 
                                    role="alert">
                                    <strong>
                                        {{ $message }}
                                    </strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        
                        
                        
                        
                          <div 
                            class="form-group row"
                            >
                            <label 
                                for="project" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Empresa que ofrece el servicio') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >
                                <select 
                                    class="custom-select  @error('project') is-invalid @enderror"
                                    id="project" 
                                    name="project"
                                    required>

                                    <option></option>
                                    
                                    @foreach($projects as $project)
                                        <option
                                            value = "{{$project->id}}"
                                            >{{$project->decorate()->name()}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>
                            @error('project')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $project }}</strong>
                            </span>
                            @enderror

                        </div>
                        
                        
                        
                         <div 
                            class="form-group row"
                            >
                            <label 
                                for="priority" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Prioridad de la tarea') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >
                                <select 
                                    class="custom-select  @error('priority') is-invalid @enderror"
                                    id="priority" 
                                    name="priority"
                                    >
                                    
                                    @foreach(\App\Task::PRIORITY_ARRAY as $priority)
                                        <option
                                            value = "{{$priority}}"
                                            >{{(new \App\Task())->decorate()->priority($priority)}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>
                            @error('priority')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $priority }}</strong>
                            </span>
                            @enderror

                        </div>
                        
                        
                        <div 
                            class="form-group row"
                            >
                            <label 
                                for="user" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Usuario  ') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >
                                <select 
                                    class="custom-select  @error('user') is-invalid @enderror"
                                    id="user" 
                                    name="user"
                                    required>

                                    <option></option>
                                    
                                    @foreach($users as $user)
                                        <option
                                            value = "{{$user->id}}"
                                            >{{$user->decorate()->name()}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>
                            @error('user')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $user }}</strong>
                            </span>
                            @enderror

                        </div>
                        
                        
                        
                        
                        <div 
                            class="form-group row mb-0"
                            >
                            <div 
                                class="col-md-6 offset-md-4"
                                >
                                <button 
                                    type="submit" 
                                    class="btn btn-primary"
                                    >
                                    {{ __('Crear') }}
                                </button>
                            </div>
                        </div>


                    </form>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/task/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="cabecera">Bienvenido {{$user->name}} {{$user->last_name}} </div>

                <div class="card-body text-center">

                    <div class="col-lg-12 align-self-baseline ">
                        <p class=" font-weight-light mb-5"> Es un gusto tenerte por aquí de nuevo! </p>
                    </div>




                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/task/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="cabecera"> 
                    
                     Tareas
                
                </div>
                
               
                
                <div class="card-body ">
                    
                    
                     <p>
                        Tabla con las tareas existentes.  
                    </p>
                    
                    <a 
                        class='btn btn-warning my-3'
                        href="{{route('task.create')}}"
                        >
                           Crear Tarea
                    </a>

                   @include('models.task.index')



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/task/index.blade.php
                    <table class='table table-sm table-striped ' >
                        <thead class='thead-dark '>
                            <tr>
                                <th>
                                    id
                                </th>
                                <th>
                                    Nombre
                                </th>
                               
                                <th>
                                    Proyecto
                                </th>
                                <th>
                                    Prioridad
                                </th>
                                <th>
                                    Encargado
                                </th>
                                <th>
                                    Estado
                                </th>
                                <th>
                                    Fecha de incio
                                </th>
                                <th>
                                    Fecha de finalizacion
                                </th>

                                <th>
                                    Fecha Creacion
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ( $tasks as $task )

                            <tr>
                                <th>
                                    {{$task->id}}
                                </th>
                                <th>
                                    {{ $task->decorate()->nameLink()}}
                                </th>
                              
                                <th>
                                    {{ $task->decorate()->project()}}
                                </th>
                                <th>
                                    {{ $task->decorate()->priority()}}
                                </th>
                                <th>
                                    {{ $task->decorate()->assigned_to()}}
                                </th>
                                <th>
                                    {{ $task->decorate()->status()}}
                                </th>
                                <th>
                                    {{ $task->started_at}}
                                </th>
                                <th>
                                    {{ $task->finished_at}}
                                </th>

                                <th>
                                    {{ $task->created_at}}
                                </th>


                            </tr>

                            @endforeach
                        </tbody>
                    </table>