routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/*
  DB::listen(function ($query){
  echo "<pre> {$query->sql} </pre>";
  });
 */

Route::get('/reset', function () {
    echo Artisan::call("migrate:refresh");
    echo Artisan::call("db:seed");
    return "PAGINA RESETEADA";
});

Route::get('/', function (Illuminate\Http\Request $request) {
    //dd($request->session()->all());
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

 Route::get('/sychronize', 'SychronizeController@synchronize')->name('sychronize');
 Route::get('/api/projects', 'FreedCampAPI\ProjectsAPIController@index')->name('api.projects');
 Route::get('/api/task', 'FreedCampAPI\TaskAPIController@index')->name('api.task');

Route::middleware('auth')->namespace('Resource')->group(function() {
    
   
    
    Route::resource('project', 'ProjectController');
    Route::resource('contract', 'ContractController');
    Route::resource('enterprise', 'EnterpriseController');
    Route::resource('task', 'TaskController');
    Route::resource('enterpriseservice', 'EnterpriseServiceController');
    Route::resource('client', 'ClientController');
    Route::resource('service', 'ServiceController');
    Route::resource('user', 'UserController');
    
    
    Route::GET('contract/{contract}/changeStatus/{status}' , 'ContractController@changeStatus')
            ->name('contract.changeStatus');
    
    Route::GET('task/{task}/changeStatus/{status}' , 'TaskController@changeStatus')
            ->name('task.changeStatus');
    
    Route::GET('project/{project}/setContract/{contract}' , 'ProjectController@setContract')
            ->name('project.setContract');
    
});

app/Contract.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contract extends Model {

    protected $table = 'contracts';
    public $timestamps = true;

    const STATUS_IN_PROGRESS = 1;
    const STATUS_ENDED = 0;
    
    protected $with = ['enterprise' , 'service' , 'client'];

    public function projects() {
        return $this->hasMany('App\Project', 'contract_id', 'id');
    }

    public function enterprise() {
        return $this->belongsTo('App\Enterprise', 'enterprise_id', 'id');
    }

    public function service() {
        return $this->belongsTo('App\Service', 'service_id', 'id');
    }

    public function client() {
        return $this->belongsTo('App\Client', 'client_id', 'id');
    }

    public function decorate(){
        return new \App\Decorators\ContractDecorator($this);
    }
}

app/Http/Controllers/Resource/ContractController.php
<?php

namespace App\Http\Controllers\Resource;

use App\Http\Controllers\Controller;
use App\Contract;
use App\Enterprise;
use App\Client;
use App\Service;
use Illuminate\Http\Request;
use App\Http\Requests\ContractCreateRequest;

class ContractController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $contracts = Contract::get();
        return view('models.contract.home', compact('contracts'));
    }

    public function changeStatus(Contract $contract, $status) {

        if ($status == Contract::STATUS_ENDED) {
            $contract->status = Contract::STATUS_ENDED;
        } else if ($status == Contract::STATUS_IN_PROGRESS) {
            $contract->status = Contract::STATUS_IN_PROGRESS;
        } else {
            $error = ["error"];
            return back()->withErrors($error);
        }
        $contract->save();
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $enterprises = Enterprise::get();
        $clients = Client::get();
        $services = Service::get();
        return view('models.contract.create', compact(
                        'enterprises', 'services', 'clients'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContractCreateRequest $request) {
        $contract = new Contract();
        $contract->enterprise_id = $request->input('enterprise');
        $contract->client_id = $request->input('client');
        $contract->service_id = $request->input('service');
        $contract->status = Contract::STATUS_IN_PROGRESS;
        $contract->save();
        return redirect()->route('contract.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function show(contract $contract) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function edit(contract $contract) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, contract $contract) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\contract  $contract
     * @return \Illuminate\Http\Response
     */
    public function destroy(contract $contract) {
        //
    }

}

resources/views/models/contract/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="cabecera"> Crear un Contrato Nuevo </div>

                <div class="card-body text-center">

                    <form method="POST" action="{{ route('contract.store') }}"  enctype="multipart/form-data">
                        @csrf


                        <div 
                            class="form-group row"
                            >
                            <label 
                                for="enterprise" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Proyecto') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >
                                <select 
                                    class="custom-select  @error('enterprise') is-invalid @enderror"
                                    id="enterprise" 
                                    name="enterprise"
                                    required>

                                    <option></option>
                                    
                                    @foreach($enterprises as $enterprise)
                                        <option
                                            value = "{{$enterprise->id}}"
                                            >{{$enterprise->decorate()->name()}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>
                            @error('enterprise')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $enterprise }}</strong>
                            </span>
                            @enderror

                        </div>

                        
                        
                        
                        
                        <div 
                            class="form-group row"
                            >
                            <label 
                                for="client" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Cliente') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >
                                <select 
                                    class="custom-select  @error('client') is-invalid @enderror"
                                    id="client" 
                                    name="client"
                                    required>

                                    <option></option>
                                    
                                    @foreach($clients as $client)
                                        <option
                                            value = "{{$client->id}}"
                                            >{{$client->decorate()->name()}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>
                            @error('client')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $client }}</strong>
                            </span>
                            @enderror

                        </div>
                        
                        
                        
                         <div 
                            class="form-group row"
                            >
                            <label 
                                for="service" 
                                class="col-md-4 col-form-label text-md-right">
                                {{ __('Servicio que se ofrece') }}
                            </label>
                            <div 
                                class="col-md-6"
                                >
                                <select 
                                    class="custom-select  @error('service') is-invalid @enderror"
                                    id="service" 
                                    name="service"
                                    required>

                                    <option></option>
                                    
                                    @foreach($services as $service)
                                        <option
                                              value = "{{$service->id}}"
                                            >{{$service->decorate()->name()}}</option>
                                    @endforeach
                                    
                                </select>
                            </div>
                            @error('service')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $service }}</strong>
                            </span>
                            @enderror

                        </div>
                        
                        
                        
                        <div 
                            class="form-group row mb-0"
                            >
                            <div 
                                class="col-md-6 offset-md-4"
                                >
                                <button 
                                    type="submit" 
                                    class="btn btn-primary"
                                    >
                                    {{ __('Crear') }}
                                </button>
                            </div>
                        </div>


                    </form>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/contract/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="cabecera">Bienvenido {{$user->name}} {{$user->last_name}} </div>

                <div class="card-body text-center">

                    <div class="col-lg-12 align-self-baseline ">
                        <p class=" font-weight-light mb-5"> Es un gusto tenerte por aquí de nuevo! </p>
                    </div>




                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/contract/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="cabecera">                    
                    <h4>
                        Contratos
                    </h4>
                
                </div>
                
                <div class="card-body ">
                    
                    <p>
                        Tabla con los contratos existentes.  
                    </p>
                    
                    <a 
                        class='btn btn-warning my-3'
                        href="{{route('contract.create')}}"
                        >
                           Crear contrato
                    </a>
                    
                   @include('models.contract.index')


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/models/contract/index.blade.php
<table class='table table-sm table-striped ' >
    <thead class='thead-dark '>
        <tr>
            <th>
                id
            </th>

            <th>
                Empresa
            </th>

            <th>
                Cliente
            </th>

            <th>
                Servicio
            </th>

            <th>
                Estado
            </th>

            <th>
                Fecha Creacion
            </th>


            <th>
                Fecha Actualizacion
            </th>


        </tr>
    </thead>
    <tbody>
        @foreach ($contracts as $contract )

        <tr>
            <th>
                {{$contract->id}}
            </th>

            <th>                                        
                {{$contract->decorate()->enterprise()}}
            </th>

            <th>
                {{$contract->decorate()->client()}}
            </th>

            <th>
                {{$contract->decorate()->service()}}
            </th>

            <th>
                {{$contract->decorate()->status()}}
            </th>

            <th>
                {{$contract->created_at}}
            </th>

            <th>
                {{$contract->updated_at}}
            </th>                                   


        </tr>

        @endforeach
    </tbody>
</table>